# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9a6ae21e2a075c5335714a91787c5728897c88f543befecdf535952ffd82ea5038cbad47436d4a194c0b5caf23b76f06893b48eb397f8eedc803fdba599240a

test:
  secret_key_base: fb225917b507a6baecbbc7c2b273de2d201d8f378c5dfd0ffd4c080e9aec4d3772e794fff8164af6d9577e33fb12747a22d2b15b9f5f64cc0cd52d4433ab8154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
